name: susscan

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Install Sustainability Scanner and dependencies
        run: |
          python3 -m venv venv
          source venv/bin/activate
          pip install sustainability-scanner

      - name: Install Rust and cfn-guard
        run: |
          curl https://sh.rustup.rs -sSf | sh -s -- -y
          source $HOME/.cargo/env
          cargo install cfn-guard

      - name: Run Sustainability Scanner with custom rules
        run: |
          source venv/bin/activate
          susscanner ./fixed.yaml\
            -r venv/lib/python3.12/site-packages/susscanner/rules_metadata.json

