name: susscan

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install sustainability-scanner

      - name: Run Sustainability Scanner with custom rules
        run: |
          source venv/bin/activate
          sustainability-scanner \
            -t ./fixed.yaml \
            -r venv/lib/python3.12/site-packages/susscanner/rules_metadata.json

